// <auto-generated />
using BlazorEcommerce.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorEcommerce.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220206202709_CreateInitial")]
    partial class CreateInitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BlazorEcommerce.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "dsfsdfsdfdsxzfdfsdf",
                            ImageUrl = "https://livedemo00.template-help.com/wt_prod-19881/images/book-1-210x325.png",
                            Price = 10m,
                            Title = "Book1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "4f324f32sdsasef",
                            ImageUrl = "https://livedemo00.template-help.com/wt_prod-19881/images/book-2-210x325.png",
                            Price = 20m,
                            Title = "Book2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "432f4fjghjfgrtrtet",
                            ImageUrl = "https://livedemo00.template-help.com/wt_prod-19881/images/book-3-210x325.png",
                            Price = 30m,
                            Title = "Book3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
